### ISSUE TITLE
Errore : Unknown letter - C

### ISSUE THREAD

**Issue by Deltaplc** [obzerving/hlines#1]
Good morning
I installed your extension in and can't get it to work!
This is the error: Unknown letter - C.
can you help me?
Thank you
David

**Comment by Deltaplc** [comment]
Sorry, trying again I realized it only works with straight lines!
Right?
Can you give me directions for something that has the same functions but also on curved lines !?
Thank you

**Comment by obzerving** [comment]
You are correct that this extension (and every other one in this repository) requires straight lines. I'm not aware of any extensions that perform this function on curved lines.

**Comment by obzerving** [comment]
The latest version of this extension allows for a mix of straight lines and curves. This is my first attempt at processing Curve path commands, so good luck to all.

**Comment by Deltaplc** [comment]
Thank you so much for your help!
Greetings
David
